sudo: false
language: node_js
node_js:
  - "7"

addons:
  apt:
    packages:
    - gcc-6

# cache:
#   directories:
#     # - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov
